### PR TITLE
Some enhancement concerning conformance unit tests.

### PR DESCRIPTION
**Pull request by cjundt**

### CODE REVIEW

**Comment by JeffFerguson** [comment]
Thank you for submitting this! I have two initial concerns:

- Pull requests should go against the `develop` branch rather than the `master` branch.
- I am concerned that the PR modifies the `xbrl.xml` file, as that comes directly from the XBRL organization. If you go to https://specifications.xbrl.org/work-product-index-group-base-spec-base-spec.html and look at the [Conformance Suite ZIP file](http://www.xbrl.org/2014/XBRL-CONF-2014-12-10.zip), you will find that the `xbrl.xml` file is included in that distribution. The Gepsio test base respects the existing structure of the contents of that ZIP such that, should a new suite be released, I can "drop in" the new Suite and have the code work as-is. My concern is that, should a new Conformance Suite be released, the new Suite could not be "dropped in" and would require some modification. I'll give that one some thought.

**Comment by cjundt** [comment]
Hi,
**Concerning your second point**: You're right, I'll find another way. I already have some ideas. I'll add a commit soon.
**Concerning your first point**: It should be the case or am I missing some thing ?
image

**Comment by JeffFerguson** [comment]
Regarding the branch merges, when I look at the top of this pull request page, I see this:

image

I was concerned because it said `JeffFerguson:master` rather than `JeffFerguson:develop`, so I thought that I would ask about it.

**Comment by cjundt** [comment]
Oh, yes, my mistake! I didn't change the destination branch when I made the pull request.
Sorry for that!

**Pull request closed without merging**
